{
 "title": "DNS Status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "humanname",
    "query": {
     "query": "label_values(probe_dns_duration_seconds,humanname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime by DNS Request",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{humanname=~\"$humanname\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime by DNS Server",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "probe_success{instance!=\"localhost\"}",
     "legendFormat": "{{humanname}}"
    }
   ]
  },
  {
   "title": "DNS Request by Phase (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(probe_dns_duration_seconds) by (phase) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Request by Server (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(probe_dns_duration_seconds) by (humanname)",
     "legendFormat": "{{humanname}}"
    }
   ]
  },
  {
   "title": "DNS Request by Lookup (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(probe_dns_duration_seconds) by (lookup) > 0",
     "legendFormat": "{{humanname}}"
    }
   ]
  }
 ]
}